# Generated by Django 3.1.5 on 2021-03-05 04:46

from django.db import migrations, models
import rh.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_funcional', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=120, validators=[rh.validators.verify_cpf])),
                ('naturalidade', models.CharField(max_length=120)),
                ('cor', models.CharField(max_length=120)),
                ('nome_mae', models.CharField(max_length=120)),
                ('data_nascimento', models.CharField(max_length=120)),
                ('foto_3x4', models.ImageField(upload_to='../static/upload/fotos3x4/', validators=[rh.validators.validate_foto])),
                ('comprovante_residencia', models.FileField(upload_to='../static/upload/comprovantesResidencia/', validators=[rh.validators.validate_comprovante])),
                ('rg', models.CharField(max_length=120)),
                ('orgao_emissor', models.CharField(max_length=120)),
                ('uf_rg', models.CharField(max_length=120)),
                ('data_emissao_rg', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=120)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=120)),
                ('telefone_residencial', models.CharField(blank=True, max_length=120)),
                ('telefone_celular', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_funcional', models.CharField(max_length=120)),
            ],
        ),
    ]
