# Generated by Django 3.1.5 on 2021-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20210207_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
