# Generated by Django 3.1.5 on 2021-02-07 19:41

from django.db import migrations, models
import rh.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_auto_20210207_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf2',
            field=models.IntegerField(default=4, validators=[rh.models.verify_cpf]),
            preserve_default=False,
        ),
    ]
