# Generated by Django 3.1.5 on 2021-02-07 20:11

from django.db import migrations, models
import rh.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_remove_funcionario_cpf2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=120, validators=[rh.models.verify_cpf]),
        ),
    ]
