# Generated by Django 3.1.5 on 2021-02-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_auto_20210207_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_funcional', models.CharField(max_length=120)),
            ],
        ),
    ]
