# Generated by Django 3.1.5 on 2021-02-14 19:58

from django.db import migrations, models
import rh.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_funcionarioquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='comprovante_residencia',
            field=models.FileField(upload_to='../static/upload/comprovantesResidencia/', validators=[rh.validators.validate_comprovante]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto_3x4',
            field=models.ImageField(upload_to='../static/upload/fotos3x4/', validators=[rh.validators.validate_foto]),
        ),
    ]
