# Generated by Django 3.1.5 on 2021-02-11 04:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem_processo', models.CharField(max_length=120)),
                ('tipo_processo', models.CharField(max_length=120)),
                ('assunto_detalhado', models.TextField(max_length=900)),
                ('natureza_processo', models.CharField(choices=[('OSTENSIVO', 'OSTENSIVO'), ('RESTRITO', 'RESTRITO')], default='OSTENSIVO', max_length=120)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=120)),
                ('unique_documento_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(blank=True, upload_to='../static/upload/%Y/%m/%d/')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='infra.processo')),
            ],
        ),
    ]
