# Generated by Django 3.1.5 on 2021-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_processo1', models.CharField(max_length=120)),
                ('origem_processo', models.CharField(max_length=120)),
                ('tipo_processo', models.CharField(max_length=120)),
                ('assunto_detalhado', models.TextField(max_length=900)),
                ('natureza_processo', models.CharField(choices=[('OSTENSIVO', 'OSTENSIVO'), ('RESTRITO', 'RESTRITO')], default='OSTENSIVO', max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('documentos', models.FileField(blank=True, upload_to='../static/upload/pdfs/')),
            ],
        ),
    ]
