# Generated by Django 3.1.5 on 2021-03-05 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='responsavel',
            field=models.ForeignKey(on_delete=models.SET('Sem responsavel'), related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setor', to='infra.setor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='infra.processo'),
        ),
    ]
