# Generated by Django 3.1.5 on 2021-02-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='documentos',
        ),
    ]
