# Generated by Django 3.1.5 on 2021-02-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20210214_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=120)),
                ('filter_field', models.CharField(choices=[('NATUREZA_PROCESSO', 'NATUREZA_PROCESSO'), ('unique_id', 'unique_id'), ('origem_processo', 'origem_processo'), ('tipo_processo', 'tipo_processo'), ('natureza_processo', 'natureza_processo'), ('responsavel', 'responsavel')], default='unique_id', max_length=120)),
            ],
        ),
    ]
