# Generated by Django 3.1.5 on 2021-03-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20210305_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='natureza_processo',
        ),
    ]
