# Generated by Django 3.2 on 2021-04-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20210309_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespatchReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_processo', models.CharField(choices=[('Enviar', 'Enviar'), ('Receber', 'Receber')], max_length=40)),
                ('status_processo', models.CharField(blank=True, default='False', max_length=40)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_procesos', to='infra.processo')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_setor', to='infra.setor')),
            ],
        ),
    ]
