# Generated by Django 3.1.5 on 2021-02-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_auto_20210204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='documentos',
            field=models.FileField(upload_to='static/uploads/pdfs/'),
        ),
    ]
