# Generated by Django 3.1.5 on 2021-02-09 01:44

from django.db import migrations, models
import django.db.models.deletion
import infra.models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_auto_20210208_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='documentos',
        ),
        migrations.CreateModel(
            name='ProcessoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.FileField(blank=True, upload_to=infra.models.content_file_name)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='infra.processo')),
            ],
        ),
    ]
