# Generated by Django 3.1.5 on 2021-02-09 02:03

from django.db import migrations, models
import infra.models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20210208_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='documentos',
            field=models.FileField(blank=True, upload_to=infra.models.content_file_name),
        ),
        migrations.DeleteModel(
            name='ProcessoDocumento',
        ),
    ]
