# Generated by Django 3.1.5 on 2021-02-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_auto_20210204_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='documentos',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
