# Generated by Django 3.1.5 on 2021-02-05 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_auto_20210204_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='id',
        ),
        migrations.AddField(
            model_name='processo',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processo',
            name='documentos',
            field=models.FileField(upload_to='../static/upload/pdfs/'),
        ),
    ]
