# Generated by Django 3.1.5 on 2021-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_auto_20210204_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='processo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
