# Generated by Django 3.1.5 on 2021-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0008_auto_20210206_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='natureza_processo',
            field=models.CharField(choices=[('OSTENSIVO', 'OSTENSIVO'), ('RESTRITO', 'RESTRITO')], default='OSTENSIVO', max_length=120),
        ),
    ]
